### ISSUE TITLE
schickeres Loadpic

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_EndGame_Template.Stratis#15]
**Ideensammlung:**
- Darstellung der drei Phasen (FOB -> Intel -> Schematics)
- Darstellung der drei Parteien
  - Problem: Parteien können in jeder Mission unterschiedlich sein
  - Lösung(?): Nur die Köpfe abbilden. Links Bluforspieler im Profil, Mitte KI, rechts Opforspieler im Profil.
- EndGame Upload Kistenterminaldingens
  - Problem: Uploadobjekt kann in jeder Mission anders aussehen
- Schematics. Dieser Ordner mit "Top Secret" auf einem Schreibtisch liegend.
- Aufnahme einer FOB aus Vogelperspektive, angelehnt an diese kreisende Kameraeinstellung am Missionsbeginn
- ...

**Comment by McDiod** [comment]
@nomisum : Kannst ja mal gucken, ob irgendwas davon umsetzbar ist <3

**Comment by nomisum** [comment]
bin noch nicht dazu gekommen, wird aber noch :)
